### ISSUE TITLE
OpenKh.Command.HdAssets Does Not Support PS3 Variants

### ISSUE THREAD

**Issue by Vladabdf** [OpenKH/OpenKh#100]
Both the "extract" and "strip" command arguments do nothing with PS3 assets. I have only tested this with 2.5 (KH2) however, as I don't have a hashlist to dump 1.5 or BbS HD.

**Comment by Xeeynamo** [comment]
Does it work with PS4 remsters?

**Comment by Vladabdf** [comment]
Works perfectly fine on all PS4 remasters I tried it on, though I have yet to try DDD. I will do that real quick.

**Comment by Xeeynamo** [comment]
Probably PS3 remasters uses some weird big endian stuff

**Comment by Rikux3** [comment]
System.ArgumentOutOfRangeException: Not negative number needed.
The HdAsset header is all big endian :/

**Comment by Xeeynamo** [comment]
A quick idea that comes in my mind is to manually check if the first integer is greater than 0x1000000 to check the endian-ness to load the right endian for BinaryMapper. Hacky, but it does the trick and we do not have to bother about HdAssets ever anymore.
BinaryMapper has to be updated to 1.5.0 across the entire solution though.

**Comment by Vladabdf** [comment]
No need for the support anymore; PS3 and PS4 versions are considered deprecated as of the PC release, and supporting the PS3 copies of the games is honestly too much effort that would be met with no fanfare whatsoever.

**Comment by Delta-473** [comment]
Imho would still be a nice to have eventually.
