### ISSUE TITLE
":" Character clears all input for file path selection, unable to use mod manager in build 1112 and beyond

### ISSUE THREAD

**Issue by ShadowPandah** [OpenKH/OpenKh#1060]
**OpenKH Build**
1112 - 1115

**OpenKH Program**
openkh.tools.modsmanager.exe

**Describe the Bug**
When selecting the EGS edition of KH collections, the `:` character blanks out the entire folder path selection, making it impossible to continue setting up the mod manager through EGS copies.

**To Reproduce**
1. load program
2. run wizard
3. select file path or type ":" with `PC Release via Epic Games Store` selected
4. See the error occur

**Expected behavior**
Successfully detect the selected path without said path becoming blank and unusable

**Screenshots**
N/A

**Additional context**
Happening as of [build #1112](https://github.com/OpenKH/OpenKh/releases/tag/release2-1112)

**Comment by Vladabdf** [comment]
Could you provide a screenshot where exactly this is happening? I ran the installer wizard for the mod manager and can type my game path `Z:\Games\KH_1.5_2.5\` just fine.

**Comment by Vladabdf** [comment]
@FernandoRApud Would you be able to take a look and see why this is happening? :grin:

**Comment by ShadowPandah** [comment]
it's happening on all the builds I mentioned (Steam support and beyond) and
I'm using the latest epic games version. it's not something I can really
screenshot since it's just a static blank screen, the autodetect says
"FOUND" for 1.5/2.5 and 2.8, but the slots stay blank. going to manually
type anything in the blank space works, but the moment I type ":" the entry
clears.

**Comment by FernandoRApud** [comment]
Allright, i will take a look

**Comment by ShadowPandah** [comment]
I should also mention I'm using the latest Win10 build

**Comment by FernandoRApud** [comment]
As i can see, is something about verifying the Panacea and the location
The steam version doesnt fall on that checks, but EGS yes
I wil take a look more deep to see whats happening and why

**Comment by ChaosEternalRE** [comment]
Last night I noticed that the detect installs button will detect your Steam installation when EGS is selected. It leaves the boxes unpopulated, however. Perhaps that bug is related to this?

**Comment by ShadowPandah** [comment]
yes, that is due to it being related and containing a ":" character in the
path I believe. That was part of my reported issue

**Comment by Vladabdf** [comment]
Should be fixed fully as of #1063. Please try [release 1120](https://github.com/OpenKH/OpenKh/releases/tag/release2-1120) and report back.
