### ISSUE TITLE
[BUG] - Cannot Extract 1.5 + 2.5 Content on OpenKh.Tools.ModsManager.exe

### ISSUE THREAD

**Issue by GuidingHeart** [OpenKH/OpenKh#1061]
**OpenKH Build**
release2-1115

**OpenKH Program**
OpenKh.Tools.ModsManager.exe

**Describe the Bug**
Running the wizard on the mod manager for the steam version crashes when attempting to export game's contents.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Run Wizard'
3. Enter Folder Location of Game via Steam
4. Install Panacea and click "next"
5. Configure LuaBackEnd and click "next" twice
6. Upon clicking "Extract Game Data" it immediately crashes the tool.

**Expected behavior**
I expected to either proceed without extraction or extract the game's contents with ease.

**Screenshots**

**Additional context**
The steps above are exactly how I was able to recreate this bug/issue. As of 6/17/2024 OpenKh is updated to its latest version.

**Comment by FernandoRApud** [comment]
Hello Guilding, how are you?
Just for more information, happens with any game?
And one more question, what happens if you dont install panacea and dont configure anything, just go next?
Thanks:)

**Comment by GuidingHeart** [comment]
Hi Fernando! Unfortunately it still results in a crash.

**Comment by FernandoRApud** [comment]
Excelent, thanks for your information! I will try to see more deep into this

**Comment by Vladabdf** [comment]
Should be fixed fully as of #1063. Please try [release 1120](https://github.com/OpenKH/OpenKh/releases/tag/release2-1120) and report back.

**Comment by GuidingHeart** [comment]
Hi Vlad, 

Issue has been resolved. Thank you both so much!
