### ISSUE TITLE
[BUG] - Mod Manager halted extraction of KH2 seemingly out of nowhere

### ISSUE THREAD

**Issue by Vladabdf** [OpenKH/OpenKh#1066]
### OpenKH Build
[Release 1120](https://github.com/OpenKH/OpenKh/releases/tag/release2-1120)

### Describe the bug
I began extracting KH2 from scratch and got the error in the attached image.

### To reproduce
1. Open Mod Manager
2. Run wizard
3. Select path
4. Select game
5. Extract
6. Wait
7. Wait
8. Wait
9. Wait
10. Error
11. Click `Yes` when prompted to continue
12. Wait
13. Wait
14. Wait
15. Extraction completes eventually

### Expected behavior
Extraction should complete without random interruptions.

### Screenshot
![2024-06-18_00-15-36 explorer](https://github.com/OpenKH/OpenKh/assets/20749232/f2d056b6-7325-4069-80a9-ae76a8b93969)

### Additional context
After continuing with the extraction again (clicking `Yes` in the screenshot), the error did not happen again. Extraction progress did seem to reset. I did not extract any other games, so it may be a random fault that happens occasionally which could safely be ignored by most users, however it would be awfully annoying if it happened multiple times back to back. This might cause intense anger & emotional distress, and even potentially create the desire to burn the user's PC.

**Comment by TheSoraHD** [comment]
Can you reproduce the issue again? I had tried once on a Windows 10 with Steam (just verified files) and [Release 1120](https://github.com/OpenKH/OpenKh/releases/tag/release2-1120) and found no problem at all during the extraction process. I have yet to try with Steam Deck, though.

**Comment by shananas** [comment]
I didn't even know this message box existed so I'd assume this was from xeeynamo to catch an error in extraction likewise i do not really understand the extraction code. Before my PR i tested both extraction in a Debug version and Release version with no issue it would seem theres just a chance of this and looking at the code if it fails to find one file it restarts the entire extraction `Line 687 in SetupWizardViewModel.cs`
So idk what to do about this

**Comment by Vladabdf** [comment]
I wasn't able to reproduce it either. Honestly, the biggest issue with it is that the extraction process started over. I'm not sure if it's inherently possible to fix that, given the code's current state, and this is such a low priority issue that I wouldn't stress about it too much. It was more annoying than anything, and my extraction completed after retrying.
