### ISSUE TITLE
[BUG] - Linux: LuaBackend not working in Mods Manager, 24.07.17.0

### ISSUE THREAD

**Issue by JayH2971** [OpenKH/OpenKh#1083]
**OpenKH Build 24.07.17.0**

**Mods Manager Program**

**Describe the Bug**
I used to use LuaBackend on this computer, but after an away period of a few months, some update has changed things. Installing LuaBackend via the mods manager does not create function for Lua-based mods. I have attempted with GOA Randomizer, Autosave, and Soft Reset. I have removed and re-installed LuaBackend multiple times but with no result.

**To Reproduce**
1. "Run Wizard" in mods manager
2. Select KH2 in LuaBackend page, install
3. Add Lua-based KH2 mods
4. Start game, mods not functioning

**Expected behavior**
Autosave and Soft Reset would create an alternate save file or allow a controller reset, respectively. GOA would load each world from a distinct starting point.

**Screenshots**
![Screenshot at 2024-07-19 03-50-05](https://github.com/user-attachments/assets/64ea26cf-857f-4541-a52b-bdcfd1bcaa3f)
![Screenshot at 2024-07-19 03-50-43](https://github.com/user-attachments/assets/644bae71-5007-47aa-ba1e-e9fc8de3317f)
![Screenshot at 2024-07-19 03-51-00](https://github.com/user-attachments/assets/258d8dc8-7860-4e09-91e8-75bdec371e22)
![Screenshot at 2024-07-19 03-51-10](https://github.com/user-attachments/assets/d964b1cc-1e9c-4bc2-a46b-b1448aceb9a1)
![Screenshot at 2024-07-19 03-53-04](https://github.com/user-attachments/assets/8d9ffb10-f65a-458d-a417-b9bd7a2a4198)

**Additional context**
Linux Mint
Epic Games Store
Heroic 2.41.1
Soft Reset/Autosave 2.0
GOA Randomizer 1.54.1
I tried adding Panacea for Linux but with it, KH2 refuses to boot at all. It remains active in the Heroic launcher but never brings up a window.
I added DLL overrides for version, lua54, and luabackend in Winecfg through Heroic.

**Comment by JayH2971** [comment]
Thanks for looking into that. I decided to download and try some 1FM mods that were updated now, to see if Lua could work on them. They aren't functioning either. Screenshots show health bar (expected to be 1 but is normal; also tried on a new game with same result), and gummi map (travel should be instant and have no warp drive). Soft reset via autosave lua also doesn't work.

![Untitled](https://github.com/user-attachments/assets/87bd59bb-3f63-485d-89fe-dc17e53f0e88)
![Screenshot at 2024-07-30 15-53-28](https://github.com/user-attachments/assets/91433325-1ff3-4d92-9347-85a2bd695d22)
![Screenshot at 2024-07-30 15-52-52](https://github.com/user-attachments/assets/8ddeeedb-73a4-4a27-bed2-834da114a27c)
![Screenshot at 2024-07-30 15-52-28](https://github.com/user-attachments/assets/a84f7ca5-0127-4779-ba6e-b6718124fde5)

**Comment by JayH2971** [comment]
I went to the LuaBackend repository and downloaded DBGHelp.dll from there, and renamed it dinput8 like before. With that, the Lua files are working; I have autosave and soft reset working in KH2 now. Rando also seems to work, though I encountered a strange glitch in Sim TT. About an hour in and things seem stable.

**Comment by shananas** [comment]
Looking back at this issue the setup wizard install of Lua Backend is for use with panacea if you do not use install panacea you will need to rename the file named `LuaBackend.dll` to whatever linux needs `DBGHELP.dll` which iirc is for windows or `version.dll` or `dinput8.dll` for linux.
it says as much on the Lua Backend window `Lua Backend is installed! for use with Panacea.
closing as if you intend to use with patching manual installation is required.
