### ISSUE TITLE
[BUG] - Doesn’t recognize file location on steam release when using wine 

### ISSUE THREAD

**Issue by Hikikomar1** [OpenKH/OpenKh#1102]
**OpenKH Build**
1196

**OpenKH Program**
Mod Manager

**Describe the Bug**
When using a wine program on steam deck, the mod manager doesn’t recognize the file location for the steam release of 1.5 + 2.5. I think I was using q4wine.

**To Reproduce**
1. Go to the mod manager.
2. Click on the pc release on steam.
3. Paste the folder location of 1.5 + 2.5.

**Expected behavior**
I should be able to click the next button.

**Additional context**
It could be the program that I’m using.

**Comment by Frozenreflex** [comment]
Are you using the Windows style directory path (example, ``Z:/mnt/LocalDisk2/SteamLibrary/steamapps/common/KINGDOM HEARTS -HD 1.5+2.5 ReMIX-`` for my Linux desktop)?

**Comment by Hikikomar1** [comment]
It was /home/deck/.local/share/Steam/steamapps/common/KINGDOM HEARTS -HD 1.5+2.5 ReMIX-

**Comment by Hikikomar1** [comment]
Okay so not only did I stupidly moved the steam folder to the desktop which broke steam, I couldn’t find the area in the z: drive like you said

**Comment by caomhe** [comment]
I'm experiencing the same issue. When I craft my filename as Vladabdf shows (done this several times), I get a "file not found." My theory is that perhaps it's not seeing it because it's a hidden file? I can't navigate to it from the browse directory for the same reason.

**Comment by caomhe** [comment]
Finally got it: you have to open the mod manager in Steam, run it with Proton-GE, then use Protontricks in desktop mode to install Dotnet 6 DESKTOP. Use Protontricks to run the mod manager, and it will autodetect.

**Comment by Hikikomar1** [comment]
Oh no it’s fine. I haven’t tried it yet but I will today.

**Comment by Hikikomar1** [comment]
Wait which proton-GE version is it?

**Comment by Hikikomar1** [comment]
I’m trying to open it with proton tricks but it won’t work so what now?

**Comment by Hikikomar1** [comment]
Okay it works. I was on beta so I had to switch back to normal mode then it worked. Thank you!
