### ISSUE TITLE
[BUG] - KH1 Broken Mods?

### ISSUE THREAD

**Issue by 0Tommie0** [OpenKH/OpenKh#1124]
**OpenKH Build**
24.12.0.1.0

**OpenKH Program**
Playable_KH1_Kairi and my other installed mods. LUA script add-ons still work.

**Describe the Bug**
The system shows my mods load as default with no issues on build and run, but the changes don't take place ingame.

**To Reproduce**
1. Go to 'Mod Loader'
2. Click on 'Build and Run'
3. Scroll down to 'Before the above I set to highest priority and check boxes'
4. No error appears. It's just that nothing happens aside from the vanillah game itself loading.

**Expected behavior**
Replace Sora with Kairi.

**Screenshots**
N/A as  the game loads normally seemingly unmodded aside from working LUA Scripts.

**Additional context**
Happened after updating to the latest version of OpenKH for KH1. The only thing I  haven't tried is to reinstall the application itself. I've already reinstalled the mods twice and performed reboots to no avail. Mods stopped working yesterday 12/10/2024.

**Comment by 0Tommie0** [comment]
Tried it with new update 24.12.0.11.0 still same issue. Maybe it's just me. I'll reinstall the program after work.

**Comment by Delta-473** [comment]
issuer reported it as fixed.
