### ISSUE TITLE
Mapgen doesn't optimize DOCT enough.

### ISSUE THREAD

**Issue by Disgustor** [OpenKH/OpenKh#220]
Maps still lag even after the DOCT optimization. It isn't to do with the collision, which is what I thought it was at first. I would suggest looking at how many polygons/vif packets an official mesh groups or DOCT file can contain. I'm still convinced this is the problem with the transparency flag, because if a more simple map is loaded, or if more simple models are loaded, transparency works fine.
Edit: It would also be an incredibly welcome feature to specify the different collision types, player collision, camera collision, and light collision in the .yml file. Using a separate FBX for each based on its name.

**Comment by kenjiuno** [comment]
Thanks for commenting!

To help to identify the reason of lag (high CPU load) by using unknown size of DOCT/COCT, I have experimentally added `show-stats` command to show its quantity: https://github.com/Xeeynamo/OpenKh/pull/211

> Edit: It would also be an incredibly welcome feature to specify the different collision types, player collision, camera collision, and light collision in the .yml file. Using a separate FBX for each based on its name.

OK it is good idea 👍  I'll implement it!
