### ISSUE TITLE
[FEATURE] - Additions and changes to Layout Editor

### ISSUE THREAD

**Issue by Vladabdf** [OpenKH/OpenKh#429]
This issue includes feature requests as well as bugs, but as there are more features than bugs I would like to mark it as an enhancement. As such, the details are as follows:

Enhancements:
* Add animation layer reordering through click & drag or an up/down position button
* ~Extend the sprite group preview window by a few pixels in all directions to prevent cut off from occurring (https://i.vgy.me/43QdNh.png)~
* * Added with #872 
* ~Add a zoom option for all preview windows in the editor (THIS IS MANDATORY FOR HIGH-RESOLUTION SCREENS)~
* * Added with #870 
* ~Change the 4:3 and 16:9 bounding box display to overlay on top of the animations so they are easier to see~
* * Added long ago
* ~Add the 4:3 and 16:9 bounding box display to the sequence editor~
* * Added long ago
* ~Add the option to specify the location of the msg folder to render in text that is called from animation groups~
* * Not possible: determined by hard-coded functions in the game executable
* ~Add "add sprite" and "remove sprite" buttons to the sprite editor (VERY necessary for usability purposes)~
* * Added with #872

Bugs:
* ~UV Animation values in the sprite editor do not work when changed (They read correctly from unmodified files, but changing them to a non-0 value causes them to stop working upon saving. Adding new non-0 values do not work whatsoever)~
* * Will be appended to the editor later. A flag only needs to be set per-`sequence data` file and is already set in `layout data` files
* Fix clicking through sub-windows
* * A known bug with ImGui

**Comment by TopazTK** [comment]
#870

**Comment by TopazTK** [comment]
The 3ed point has been addressed with #870.

**Comment by TopazTK** [comment]
Points 2 and 7 were addressed in #872.

**Comment by TopazTK** [comment]
Bug 1 is just silly. Turns out the SEQD has a flag in it to enable UV animations, and all SEQDs have this turned off.
Will be fixed and appended to the Layout Editor with time.

**Comment by TopazTK** [comment]
Bug 1 was addressed in #872.

**Comment by TopazTK** [comment]
Point 1 can be handled by someone else.

**Comment by Vladabdf** [comment]
Most issues and enhancements have been addressed between #870, #871, and #872.
Happily closing!
