### ISSUE TITLE
[BUG] - First time setup wizard crashes on attempting to extract files from ISO

### ISSUE THREAD

**Issue by jhobz** [OpenKH/OpenKh#508]
**OpenKH Build**
20210723.2 and 20210626.2 (maybe more, these are the only ones we tried)

**OpenKH Program**
ModsManager

**Describe the Bug**
I'm trying to get a friend set up with OpenKH and when he gets to the step in the setup wizard to extract the ISO files, he clicks extract and the wizard starts briefly, but then crashes. It looks like _some_ of the files extract into the `data` folder, but not all.

**To Reproduce**
1. Download build 20210723.2 or 20210626.2 and extract it
2. Run OpenKh.Tools.ModsManager.exe
3. Follow the wizard using PCSX2 engine and a clean ISO, then try to extract the ISO files
4. ModsManager crashes

**Expected behavior**
Files are extracted, wizard continues.

**Additional context**
We even tried extracting the ISO via WinRAR, but the wizard did not recognize the folder as having the extracted files when we did so.

**Comment by Vladabdf** [comment]
I know it's been quite some time, but did this ever get resolved/figured out? I hadn't heard of anyone else with this issue, so there was never any follow up.

**Comment by shananas** [comment]
Closing this as its been a long time and have been able to extract ISOs on various versions since this report
