### ISSUE TITLE
[FEATURE] - Mod Manager OSX Support

### ISSUE THREAD

**Issue by epic-bruh-moment** [OpenKH/OpenKh#589]
I know this is quite a stretch, but is there any possible way to port the mod manager onto mac? I know that it uses windows based functions to work. But I just want to see whether or not its possible.

I tried using the mod manager via crossover (basically just fancier wine) and it wont work over there, so thats a gone case. However is there a command line version of the mod manager?? That acts like a patcher, if so could I be pointed to the directory of it.

**Comment by Delta-473** [comment]
There's no command line version of mod manager unfortunately.

**Comment by Xeeynamo** [comment]
The back-end is cross-plaform, only the UI is Windows-only. The real problem is that on Windows we use a very specific technique to make it working with PCSX2 and currently there is no way to achieve the same on OSX or Linux due to some PCSX2 limitations.

**Comment by TopazTK** [comment]
There is with SWIFT and C++, but doing so is a monumental pain because unlike Windows or even Linux, macOS protects program memory like no tomorrow.
In C#, however, all memory features are Windows only.

Also hey @Xeeynamo! Nice to see ya commenting on issues again :eyes:

**Comment by epic-bruh-moment** [comment]
> The back-end is cross-plaform, only the UI is Windows-only. The real problem is that on Windows we use a very specific technique to make it working with PCSX2 and currently there is no way to achieve the same on OSX or Linux due to some PCSX2 limitations.

Ah, thanks for elaborating. 

For now is it possible to create a patcher (ala the old KH2FM toolkit) that is natively compatible with OSX and Linux? 

It may not be as good as a mod manager, however it will allow for installation of mods for these other platforms and can act as a temporary solution until the linux pcsx2 build and tellowkrinkle's fork (or an officially supported osx build in the future) allow for proper memory hooking

**Comment by TopazTK** [comment]
As far as I know, the only thing to do is to clean up some Windows Code to X-Platform and recompile.
It has been done before.
But beware, the KH2FM_Toolkit is not supported by OpenKH.

**Comment by epic-bruh-moment** [comment]
> As far as I know, the only thing to do is to clean up some Windows Code to X-Platform and recompile. It has been done before. But beware, the KH2FM_Toolkit is not supported by OpenKH.

Do you have any guide for doing this? It would help a ton.
