### ISSUE TITLE
Possible licence issue with `Xceed.Wpf.Toolkit`

### ISSUE THREAD

**Issue by FroggieFrog** [OpenKH/OpenKh#615]
Because you are using a version > `3.8` of the `Xceed.Wpf.Toolkit` there could be an issue with the licence.
See this issue where the maintainer **does not** deny the issue: [xceedsoftware/wpftoolkit#1598](https://github.com/xceedsoftware/wpftoolkit/issues/1598)

Do you have other/additional information on this topic?

**Comment by Delta-473** [comment]
Well time to downgrade the version until we find a better solution.

**Comment by kenjiuno** [comment]
Extended.Wpf.Toolkit 3.7.0 ~ latest 4.4.0 and later seem to use new license. 

https://www.nuget.org/packages/Extended.Wpf.Toolkit/4.4.0/License

Extended.Wpf.Toolkit 3.6.0 seems to use MS-PL.

- https://www.nuget.org/packages/Extended.Wpf.Toolkit/3.6.0
- https://licenses.nuget.org/MS-PL
