### ISSUE TITLE
(off topic) KH editor question

### ISSUE THREAD

**Issue by bucanero** [OpenKH/OpenKh#664]
sorry to open a question here, but I couldn't post on the KH editor.

Is there any specific reason why the KH Editor does not support KH Chain of Memories for the PS3 saves? is only an offset issue or maybe is something else? I'd like to know if you have any information about it

thanks!

**Comment by bucanero** [comment]
my question was meant for @Xeeynamo

**Comment by TopazTK** [comment]
Unrelated to OpenKH.
Closing.

**Comment by bucanero** [comment]
On the README, the definition of this project is:

"Aims to centralize all the technical knowledge of the 'Kingdom Hearts' game series in one place, providing documentation, tools, code libraries, and the foundation for modding the commercial games."

I asked about modding a KH save-game, for a commercial ps3 KH game.

**Comment by TopazTK** [comment]
KHSaveEditor is **not** a part of the OpenKH suite and thus is unrelated.
Any futher persistency in this matter will cause this issue to be locked.

**Comment by Vladabdf** [comment]
By technicality, save files have little to nothing to do with modifying the game data itself. Saves are not part of OpenKH's scope at this time. If you cannot access the "Issues" section of Kingdom Save Editor, the solution is not to reach out at another project that obviously will not have your solution.

Xeeynamo has also exited OpenKH in its entirety. He will probably not be responding further to any questions or inquiries.
