### ISSUE TITLE
[FEATURE] - ModsManager support game lang other than `en`

### ISSUE THREAD

**Issue by kenjiuno** [OpenKH/OpenKh#674]
**Describe the solution you'd like**
ModsManager will be better if it supports language specifier of PC version, in case of having non `en` version of game.

**Describe alternatives you've considered**
Modify source code directly.

**Additional context**
Adding property `pcReleaseLanguage` to `mods-manager.yml`

**Comment by TopazTK** [comment]
It already does. But the mods themselves need to be made to patch them in.
You see, some mods heavily rely on the language files being accurate, such as mods that modify text, mods that add new content to a specific language, or multilingual mods.
If you have a version of the game that is supported by the mod, all dandy! If not, you will need to ask the mod author to support it instead.
Now, OpenKH may not have the file names recorded for the JP version specifically, but that needs investigation.

**Comment by kenjiuno** [comment]
Thanks for comment.
You are right. The many published mods are based on `en` version.

My motivation is simple.
Move the hardcoded `en` to yml file so that user can run/test a mod on localized version of PC version.

https://github.com/OpenKH/OpenKh/blob/917c3b776e2c163394e2cf66e136385eb87f04b4/OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs#L592

Currently I don't plan this for enjoying modding on jp version.
I just want to test generated map file made by MapGen.
I cannot guarantee full working on jp version, but ModsManager works on jp version, at least map file replacing.
