### ISSUE TITLE
[BUG] - ModsMan wizard: click back on finish page will back to second page

### ISSUE THREAD

**Issue by kenjiuno** [OpenKH/OpenKh#675]
**OpenKH Build**
```bat
git describe --tags
release-412-150-gb6a5193e
```

**OpenKH Program**
OpenKh.Tools.ModsManager

**Describe the Bug**
At wizard, click back button on finish page will bring back to game edition page.

**To Reproduce**

![2022-09-17_12h01_25](https://user-images.githubusercontent.com/5955540/190838142-8a008504-bc95-4b7d-a7f3-ae66656920da.png)

![2022-09-17_11h57_10](https://user-images.githubusercontent.com/5955540/190838094-53aeba82-4b09-4410-834a-df3c0998b6e7.png)

![2022-09-17_11h57_17](https://user-images.githubusercontent.com/5955540/190838101-020b7577-7b52-4f93-b2fd-6d392ce0a678.png)

**Expected behavior**
It prefers to back to previous wizard page on clicking back button .

**Comment by shananas** [comment]
Also if you click back on this page when setting up PC
![image](https://user-images.githubusercontent.com/47014056/190838947-a5492e77-7267-4d4b-8886-d3c5c359cc30.png)
It goes to an emulator setup page
![image](https://user-images.githubusercontent.com/47014056/190838955-3ade5558-d464-407a-a2de-df78df3bbfce.png)
