### ISSUE TITLE
[BUG] - My mods keeps asking for files within an empty "remastered" folder

### ISSUE THREAD

**Issue by KikisNO2** [OpenKH/OpenKh#694]
**OpenKH Build**
22.07.09.1

**Describe the Bug**
Most of my mods work but there are some that asks for some files within a "remastered" folder that for me its completely empty
i dont know if its an issue with my iso or if openkh siply doesnt extract that folder, it simply asks me for files that i dont have

**To Reproduce**
1. Go to 'shananas/KH2FormRando or Zurphing/Masamune '
2. Click on 'Build and Run'
3. See error

**Expected behavior**
If you have a fresh install and a clean extraction of your iso it should say "generic error" and the debug window should show the text on the screenshot
"

![image](https://user-images.githubusercontent.com/114708646/193185419-2d10ea79-c2e9-4a3d-9256-96c191d8961b.png)

if anyone has an answer to that issue im having feel free to insult my stupidity because i feel like its an obvious answer im just not seeing

**Comment by shananas** [comment]
the current mod manager release is outdated and a fair few mods especially those built with rando in mind use new features that isn't currently in a release build of Openkh mod manager on this github. For now until openkh gets auto builds done the most up to date mod manager can be found on kh2rando.com / my fork of openkh if you want to get from github

**Comment by shananas** [comment]
openkh build being restored the mod manager is now updated and supports the features these mods use.
