### ISSUE TITLE
[BUG] - Kh2MapStudio crashing (BbsMapStudio working)

### ISSUE THREAD

**Issue by AtlasKnightX** [OpenKH/OpenKh#786]
OpenKH Build
Latest Build and Build 453

OpenKH Program
OpenKh.Tools.Kh2MapStudio

Describe the Bug
On a new build install using Epic Games PC edition. In Kh2MapStudio I'll open the extracted game folder and all of the maps appear on the left. However, when selecting a map there is a one second delay while it's seemingly trying to load before the program closes without an error message. I have tried this on several different builds and maps with the same result. For whatever reason, BbsMapStudio works just fine.

To Reproduce

1. Go to Kh2MapStudio
2. Click on any map
3. Program closes, no error

Expected behavior
MapStudio loads the selected map...

Additional Context
I have an older program, Noesis, that's able to load the map files from the same /data folder.

**Comment by shananas** [comment]
I do not believe the map studio has been updated to work with the PC extraction. It does work with an ISO extraction currently. If i am correct this is more a feature request and not a BUG technically.

**Comment by AtlasKnightX** [comment]
That makes sense. Thanks for the info!
