### ISSUE TITLE
[BUG] - Tool(s) have inverted colors

### ISSUE THREAD

**Issue by Vladabdf** [OpenKH/OpenKh#825]
**OpenKH Build**
520

**OpenKH Program**
OpenKH.Tools.LayoutEditor
(possibly more) 

**Describe the Bug**
Colors on opened files with images are inverted (likely only imd & imz)

**To Reproduce**
1. Open program
2. Open file in program
3. See issue

**Expected behavior**
Colors should not be inverted. 

**Additional context**
This issue happens every so often. Are there code regressions happening under the hood that are not being documented? This must be the 10th+ time this has happened. 
For context, I only had time to test a Re:CoM layd + imz combination. I did not test KH2 or more than two additional files. Historically, when this issue happens, it occurs in all tools since they share common libraries.

**Comment by kenjiuno** [comment]
Hi sorry for inconvenience.
If you don't mind could you give me the **file name** of _Re:CoM layd_ file that you have tested.

As you mentioned this color swapping problem lies on very long period.

Primarily there is minimal documentation about pixel order. Hopefully we can check whether rest of code should apply this rule or not...

https://github.com/OpenKH/OpenKh/blob/3bd4eed0b174fd37e03ee398032c9efc404c5772/OpenKh.Imaging/IImageRead.cs#L5-L12

https://github.com/OpenKH/OpenKh/blob/3bd4eed0b174fd37e03ee398032c9efc404c5772/OpenKh.Kh2/Imgd.cs#L176-L188

**Comment by Vladabdf** [comment]
The file name of the _Re:CoM layd_ file I tested was _.\FORM\0507\FO0507.SPR\UK_title.lad_
I of course opened the accommodating _imz_ file to go with it, which contains the image data, as the _la(y)d_ file is Re:CoM's version of _seqd_

**Comment by TopazTK** [comment]
I cannot reproduce this. However, LayoutEditor cannot open the core image of the 2LD files in Sprite Editor anymore.

That bug was present since January.

**Comment by kenjiuno** [comment]
> I cannot reproduce this. However, LayoutEditor cannot open the core image of the 2LD files in Sprite Editor anymore.
> 
> That bug was present since January.

This lost functionality will be recovered by workaround #832
