### ISSUE TITLE
[FEATURE] - Mods Manager - Custom command line for running the game (i.e. support for 3rd party launchers)

### ISSUE THREAD

**Issue by CMDRNuffin** [OpenKH/OpenKh#828]
**Describe the solution you'd like**
A feature would be nice that allows me to specify my own command line to use for the "buld and run" and "run only" commands.

Ideally this would also support directly running the desired game instead of having to go through the game selector every time.

E.g. if "run through epic launcher" is not checked, show an additional checkbox "overrive command line" along with a warning that you need to know what you're doing to use that option. If that option is checked, have a text box in which the user enters the entire command line for booting up the game (e.g. `legendary launch kh2 --language=en-US`).

**Describe alternatives you've considered**
Running the game from the command line after building is tedious. So is clicking a shortcut (on the desktop or anywhere).
Simply unchecking the "run through epic launcher" option doesn't work since the EGS version needs a parent process to talk to.

**Additional context**
[Legendary](https://github.com/derrod/legendary) exists and is much better than the official Epic Games Launcher (mainly because it is open source and doesn't constantly scan your entire PC for no discernable reason), but using it requires access to the command line.

**Comment by shananas** [comment]
There will not be an option to avoid EGS it was in once or twice and brought about concerns of square attacking the project cause skipping DRM. The best we can do is what we have know which seemingly skips the launcher but actually makes panacea close it asap and load the selected game using the proper commands to the launcher.

If you chose on your end to use ways to bypass the DRM openkh cannot be attacked and that is why the checkbox is there.

**Comment by CMDRNuffin** [comment]
It's a bit sad, but that actually makes a lot of sense.
