### ISSUE TITLE
[BUG] - Panacea fails to load LuaBackend on Wine8

### ISSUE THREAD

**Issue by Kurumi78** [OpenKH/OpenKh#829]
**OpenKH Build**

release2-528

**OpenKH Program**
Panacea

**Describe the Bug**
Panacea fails to load LuaBackend.dll when using Wine 8 on Linux causing a hang on boot of Kh2.

**To Reproduce**
1.Setup OpenKH
2.Install Panacea and re-name DBGHELP.DLL to VERSION.DLL
3.Install LuaBackend
4.Rename LuaBackend's DBGHELP.dll to LuaBackend.dll
5.Set Wine's override to native,builtin for VERSION.dll
6. Run the game with Wine 8 (Im using Wine-GE-8-10)
 

**Expected behavior**
The game should launch without freezing. 

**Additional context**
This hang only occurs when launching LuaBackend through Panacea, renaming LuaBackend.dll to DINPUT8.dll and setting the wine dll override to native,builtin causes both LuaBackend and Panacea to work as intended. 

For clarity sake I also posted a similar bug report in the issue tracker for LuaBackend, found [HERE](https://github.com/Sirius902/LuaBackend/issues/10). I wasn't sure which project this issue lies in if either project chooses to fix it as it might be an issue in wine.

**Comment by Kurumi78** [comment]
> I would recommend using Wine 8 when you're running the modloader, but switching to Wine 7 when you're ready to play the game, at least for now.

Wine 8 runs the game much better for me so I'm choosing to use that. A workaround for the issue is to rename LuaBackend to DINPUT8.dll and add it as a dll override. Loading it that way seems to work fine. Doing so has allowed me to play a full randomizer so far without any issues. Panacea and LuaBackend both seem to work fine this way.

**Comment by Vladabdf** [comment]
I believe this got fixed already, so closing. If I am mistaken, it can be reopened.
