### ISSUE TITLE
[BUG] - Kh2MapStudio crashes when loading KH2 PC Maps

### ISSUE THREAD

**Issue by CodedRubyChan** [OpenKH/OpenKh#836]
**OpenKH Build**
545

**OpenKH Program**
Kh2MapStudio

**Describe the Bug**
Crashes when loading a KH2 PC Map

**To Reproduce**
1. Open Kh2MapStudio
2. Load any map from the PC Version
3. crash

**Expected behavior**
Opens the Map Viewer and all of the stuff thats editable

I know this is already known i just hope, that someone can make a fix for it

**Comment by kenjiuno** [comment]
Thanks for reporting.

_Memo_: at PC version `.ard` files are placed in different folder unlike PS2 version does.

![2023-07-31_12h20_44](https://github.com/OpenKH/OpenKh/assets/5955540/668c8c82-7c11-4e3a-846a-ccb96bbfe895)

**Comment by CodedRubyChan** [comment]
i just moved some .ard files out of their language folder (ard/gr/eh03.ard -> ard/eh03.ard) and thats literally the fix.
The Map Studio just needs to read the language subfolders.

oh and i know this may be a complicated Feature Request but now we can load the PC Files or know how: 
Could there be a feature added, where if you edit the .ard with MapStudio, so it gets written to all Language Versions?

So if you load for example eh03.map and edit something in the .ard, if the program could write it to all found versions of eh03.ard like:

ard/es/eh03.ard
ard/it/eh03.ard
ard/us/eh03.ard
ard/fr/eh03.ard
ard/gr/eh03.ard

Then i would not need to edit all of them one by one seperately

**Comment by kenjiuno** [comment]
> The Map Studio just needs to read the language subfolders.

I agree.

> Could there be a feature added, where if you edit the .ard with MapStudio, so it gets written to all Language Versions?

Writing back the modified data to each Language of `.ard` files with same file content?

I have only `jp` language asset from extracted files.
So I cannot guess whether it is good idea or not.
I want to ask that do you consider that it is really useful feature?

btw [`.ard`](https://openkh.dev/kh2/file/type/areadata.html) roughly covers these contents:

![image](https://github.com/OpenKH/OpenKh/assets/5955540/60866146-02c7-44b3-83c1-39695c4a5086)

**Comment by CodedRubyChan** [comment]
When i make mods i always want to make the mod atleast in 2 Languages, in English and German and if i find someone for translating, then even all Languages (es, fr, gr, it, us, and maybe someday even jp), and it would be easier if the modded .ard content would be written to all language versions of the same .ard, so i don't have to edit each .ard seperately.

But i can understand if thats not possible or too complicated or something, but i would like to see it as a Feature, that if there are for example six eh03.ard files (one for each of the 6 languages) that it writes the changes to all of them

**Comment by Vladabdf** [comment]
I agree, when a change is made, it should write to all languages. Maybe as a toggle that can be turned on or off?

**Comment by CodedRubyChan** [comment]
that would be the perfect solution for this

i sadly don't know enough about writing code, so i can't actually edit the code to have a function like this. 
MAYBE i could fix atleast the .ard loading but tbh, i think at the end i would break something, so i'll not try it xD
