### ISSUE TITLE
[BUG] - OpenKH Mod Manager can copy files into unintended places

### ISSUE THREAD

**Issue by adamboy7** [OpenKH/OpenKh#857]
**OpenKH Build**
Latest release, release2-599

**OpenKH Program**
OpenKh.Tools.ModsManager.exe

**Describe the Bug**
The Open KH mod manager is able to arbitrarily copy and replace files anywhere on your computer using the mod.yml file. Obviously without admin permissions some locations are off limit, but if you run mod manager as admin those work too. Variables like %appdata% and %UserProfile% also seem to kinda work. The program crashes which means this was either unexpected behavior or someone tried to avoid this, but it still manages to copy all the files you specify.

**To Reproduce**
1. Install a questionable mod from URL or a user supplied ZIP
2. Enable the mod
3. Build and patch

**Expected behavior**
The program should check that the folder it's placing files in is a relevant folder and throw an error, or at least crash BEFORE copying files.

**Example**
https://youtu.be/wUHw2WjIWPM

**Additional context**
Similar methods of placing files and folders in arbitrary places can happen when using / or ../ when downloading from a URL. For example /KH2FM-Mods-Num/GoA-ROM-Edition successfully creates a folder and clones everything to the root of whatever drive mod manager is running on, and ../../KH2FM-Mods-Num/GoA-ROM-Edition creates a folder in the same directory as mod manager but luckily fails to download and gives a file not found error.

**Comment by TopazTK** [comment]
Fixed. Thanks for your report!
