### ISSUE TITLE
[BUG] - Panacea install problem

### ISSUE THREAD

**Issue by GabrieleGiacomelli** [OpenKH/OpenKh#881]
**OpenKH Build**
OpenKh Latest Build

**OpenKH Program**
Panacea download

**Describe the Bug**
When i try to install OpenKH Panacea it give me this error "Missing Panacea Dependencies. Unable to fully install Panacea"

**To Reproduce**
1. Open KHtoolsmodmanager
2. Go till install OpenKH Panacea
3. Click on the install

**Expected behavior**
It should just install panacea

![Immagine 2023-09-17 164053](https://github.com/OpenKH/OpenKh/assets/56293277/c700d615-d9ca-47fa-984d-950e99a9cfea)

**Comment by TopazTK** [comment]
Known. Will fix.

**Comment by Vladabdf** [comment]
In the meantime, extract this file and drop its contents into your OpenKH folder.
https://discord.com/channels/409140906625728532/831437441940324377/1148621971530190848

**Comment by TopazTK** [comment]
Should be fixed with #882, no?

**Comment by Vladabdf** [comment]
My temp fix was shortly before an official fix was made, but yes. #882 fixed Panacea in its entirety.

An update + re-installation of Panacea is mandatory for the fix to take effect. Temp fix no longer works with #882.
