### ISSUE TITLE
KH2 Randomizer and GoA ROM error

### ISSUE THREAD

**Issue by WokeFox** [OpenKH/OpenKh#920]
**OpenKH Build**
3.1.1

**OpenKH Program**
Randomizer and GoA ROM

**Describe the Bug**
I get an error message for the randomizer and Goa ROM when i try to load it up. For the randomizer it says that the index was out of range. For the GoA ROM it says one or more errors have occured.

**To Reproduce**
1. I enable KH2 Randomizer, GoA ROM, and English Language Pack
2. I go to mod loader
3. I click on build and run
4. console comes up for a second
5. error messgae

**Expected behavior**
I want the game to work as intended

**Comment by Vladabdf** [comment]
Sounds like it could be a randomizer issue rather than an OpenKH one.

Your setup probably missed a step somewhere.

**Comment by WokeFox** [comment]
> Sounds like it could be a randomizer issue rather than an OpenKH one.
> 
> Your setup probably missed a step somewhere.

I might've, but i also remembered that i had downloaded PCSX2 and then realized that i downloaded the wrong version. So I removed everything from my computer, except the bois, and then downloded PCSX2-Ex using that same bios. Could this have something to do with it? Do I need a different kind of bios?

**Comment by WokeFox** [comment]
> > Sounds like it could be a randomizer issue rather than an OpenKH one.
> > Your setup probably missed a step somewhere.
> 
> I might've, but i also remembered that i had downloaded PCSX2 and then realized that i downloaded the wrong version. So I removed everything from my computer, except the bois, and then downloded PCSX2-Ex using that same bios. Could this have something to do with it? Do I need a different kind of bios?

nvm i fixed it
