### ISSUE TITLE
[FEATURE] - Generic error when I patch Chinese on language mod

### ISSUE THREAD

**Issue by zsyzlyj** [OpenKH/OpenKh#940]
I want to translate ths msg to Chinese, but a generic error said the character xx（The Chinese word） is not supported by the specified encoding.
How can I fix this error? 
![bug](https://github.com/OpenKH/OpenKh/assets/20588816/8ee4c23d-9cac-4058-8bcd-6301ddd07c13)

**Comment by TopazTK** [comment]
You need to make an entirely different encoding scheme to make Chinese Character support. Not something OpenKH can solve on it's own.
If you want to make a Chinese Translation, you need to make a new Fontimage with your characters, map them in OpenKH as a new encoding scheme (Exactly how I did so with Turkish). If you want, you can then PR this for us to check and improve.
Closing as there is nothing to be done here. If you want to take the step, we will be waiting!
